version: '2'
services:
  ssr-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9527:9527"
    command: "-s 0.0.0.0 -p 9527 -k password -m aes-256-cfb -o tls1.2_ticket_auth -O auth_sha1_v4"
    restart: always
