proxyc-cfg-data-only:
  image: kirigaya/proxychain
  volumes:
    - /opt/proxychain
  command:
    echo 'data only container'

proxychain:
  image: kirigaya/proxychain
  volumes_from:
    - proxyc-cfg-data-only
  ports:
    - "1080:1080/tcp"
    - "8123:8123/tcp"
    - "9001:9001/tcp"
  restart: always
