dnsc-cfg-data-only:
  image: kirigaya/dnschain
  volumes:
    - /opt/dnschain
  command:
    echo 'data only container'

dnschain:
  image: kirigaya/dnschain
  volumes_from:
    - dnsc-cfg-data-only
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "9000:9001/tcp"
  restart: always
